version: '2'
services:
  elasticsearch:
    image: elasticsearch
    expose:
      - 9200
    ports:
      - "9200:9200"

  kibana:
    image: kibana
    expose:
      - 5601
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
